let All_data = {
    women:[{
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/65311326_093_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/65311326_093_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"BDG High-Waisted Flare Jean—Indigo Craft",
        price:"119.00",
        discount:"15% off",
        size:"M",
        color:"rgb(60,86,113)",
        brand:"adidas",

    },
   
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/58977810_065_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/58977810_065_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Converse Chuck Taylor All Star Canvas Platform High Top Sneaker",
        price:"79.00",
        discount:"50% off",
        size:"M",
        color:"pink",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66397688_000_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66397688_000_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"UO Moon Notch Neck Top",
        price:"45.00",
        discount:"50% off",
        size:"S",
        color:"black",
        brand:"nike",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/67047191_030_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/67047191_030_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Urban Renewal Remnants Lettuce Edge Set",
        price:"95.00",
        discount:"5% off",
        size:"S",
        color:"green",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66331653_004_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66331653_004_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Urban Renewal Remnants Wide-Leg Check Pant",
        price:"49.00",
        discount:null,
        size:"M",
        color:"gray",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/65727042_030_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/65727042_030_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Urban Renewal Remnants Wide-Leg Check Pant",
        price:"29.00",
        size:"S",
        color:"green",
        color:"rgb(44,100,101)",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66211160_010_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66211160_010_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"BDG Corduroy Dipped-Waistband Pant",
        price:"75.00",
        discount:"2% off",
        size:"M",
        color:"white",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/63000095_020_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/63000095_020_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"BDG High-Waisted Skate Pant",
        price:"75.00",
        discount:"2% off",
        size:"M",
        color:"rgb(211,85,0)",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66165705_034_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66165705_034_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Out From Under Quincy Seamed Hoodie Sweatshirt",
        price:"75.00",
        discount:"2% off",
        size:"M",
        color:"rgb(194,216,147)",
        color:"green",
        brand:"nike",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66165010_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66165010_001_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"UO Rozi Blouse",
        price:"75.00",
        discount:"2% off",
        size:"M",
        color:"rgb(194,216,147)",
        color:"black",
        brand:"nike",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/63696751_060_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/63696751_060_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Wide Wale Corduroy Bucket Hat",
        price:"75.00",
        discount:"2% off",
        size:"M",
        color:"red",
        color:"rgb(194,red,147)",
        brand:"nike",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66276817_020_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66276817_020_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Out From Under Palmer Short",
        price:"75.00",
        discount:"2% off",
        size:"M",
        color:"rgb(87,40,19)",
        color:"orange",
        brand:"nike",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/67084061_000_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/67084061_000_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Out From Under Theia Striped Sleep Short",
        price:"75.00",
        discount:"2% off",
        size:"M",
        color:"white",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/65686834_105_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/65686834_105_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Out From Under Kit Lettuce Edge Short",
        price:"35.00",
        discount:"2% off",
        size:"M",
        color:"rgb(60,86,113)",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66006719_011_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66006719_011_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Out From Under Claire High-Rise Legging",
        price:"55.00",
        discount:"2% off",
        size:"M",
        color:"white",
        brand:"nike",
    },
],
shoes : [
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/59705772_055_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/59705772_055_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"Circus By Sam Edelman Marlie Platform Mule",
        price:"155.00",
        discount:"23% off",
        size:"S",
        color:"black",
        color:"rgb(157,123,204)",
        brand:"nike",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/59706382_081_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/59706382_081_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"Circus By Sam Edelman Miranda Heel",
        price:"155.00",
        discount:"23% off",
        size:"S",
        color:"orange",
        brand:"nike",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/59706382_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/59706382_001_g?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=960",
        name:"Steve Madden Lynden Patent Boot",
        price:"135.00",
        discount:"23% off",
        size:"S",
        color:"black",
        brand:"nike",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/63892038_066_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/63892038_066_h?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"UO Gina Calf Hair Platform Sandal",
        price:"75.00",
        discount:"23% off",
        size:"S",
        color:"pink",
        color:"rgb(255,0,109)",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/61478269_014_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/61478269_014_h?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"UO Cici Square Toe Mule Sandal",
        price:"55.00",
        discount:"23% off",
        size:"S",
        color:"white",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/63313084_086_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/63313084_086_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"Quoddy Barn Boot",
        price:"75.00",
        discount:"23% off",
        size:"M",
        color:"white",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/62893565_049_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/62893565_049_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"K-Swiss Match Rival Womens Sneaker",
        price:"275.00",
        discount:"23% off",
        size:"M",
        color:"white",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/64011729_010_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/64011729_010_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"adidas Ultraboost 21 Womens Sneaker",
        price:"225.00",
        discount:"23% off",
        size:"L",
        color:"white",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/62392907_049_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/62392907_049_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"adidas Ultraboost 21 Sneaker",
        price:"227.00",
        discount:"23% off",
        size:"L",
        color:"blue",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/62222062_038_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/62222062_038_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"Lacoste Match Break Sneaker",
        price:"287.00",
        discount:"23% off",
        size:"L",
        color:"rgb(44,100,101)",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/63317101_037_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/63317101_037_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"Puma Mayze Velvet Sneaker",
        price:"387.00",
        discount:"23% off",
        size:"M",
        color:"rgb(44,100,101)",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/63317101_061_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/63317101_061_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"Puma Mayze Velvet Sneaker",
        price:"387.00",
        discount:"23% off",
        size:"M",
        color:"rgb(44,100,101)",
        brand:"adorn",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/63766471_072_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/63766471_072_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"Circus By Sam Edelman Hollin Slippe",
        price:"287.00",
        discount:"23% off",
        size:"M",
        color:"yello",
        brand:"adorn",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/59705772_080_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/59705772_080_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"Circus By Sam Edelman Hollin Slippe",
        price:"227.00",
        discount:"23% off",
        size:"M",
        color:"orange",
        brand:"adorn",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/63170021_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/63170021_001_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"Circus By Sam Edelman Darren Boot",
        price:"127.00",
        discount:"23% off",
        size:"M",
        color:"black",
        brand:"adorn",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/63866362_081_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/63866362_081_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"UO Lacey Tall Boot",
        price:"137.00",
        discount:"23% off",
        size:"M",
        color:"orange",
        brand:"adorn",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/64667025_072_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/64667025_072_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"UO Brody Mono Lace-Up",
        price:"67.00",
        discount:"23% off",
        size:"M",
        color:"rgb(211,85,0)",
        brand:"adorn",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/59706382_024_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/59706382_024_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"Circus By Sam Edelman Miranda Heel",
        price:"57.00",
        discount:"23% off",
        size:"M",
        color:"rgb(181,112,69)",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/65477200_020_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/65477200_020_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=540",
        name:"Circus By Sam Edelman Miranda Heel",
        price:"57.00",
        discount:"23% off",
        size:"M",
        color:"rgb(74,24,9)",
        brand:"adidas",
    },
],
mens : [
    {
        img1:" https://images.urbndata.com/is/image/UrbanOutfitters/64816432_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/64816432_001_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"Standard Cloth Faux Leather Car Coat",
        price:"89.00",
        discount:"23% off",
        size:"M",
        color:"Black",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/64987415_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/64987415_001_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"Standard Cloth Mod Satin MA-2 Flight Jacket",
        price:"129.00",
        discount:"23% off",
        size:"M",
        color:"Black",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/65022527_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/65022527_001_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"Standard Cloth Technical Cargo Carpenter Pant",
        price:"69.00",
        discount:"23% off",
        size:"M",
        color:"Black",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/62624929_010_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/62624929_010_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"BDG Ribbed Inset Tee",
        price:"39.00",
        discount:"23% off",
        size:"M",
        color:"White",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/65021172_030_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/65021172_030_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"Knee Work Pant",
        price:"79.00",
        discount:"23% off",
        size:"M",
        color:"Green",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/61776951_083_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/61776951_083_g?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"New Balance 327 Sneaker",
        price:"100.00",
        discount:"23% off",
        size:"M",
        color:"Orange",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/55648349_014_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/55648349_014_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"Standard Cloth Oliver 5 Nylon Short",
        price:"35.00",
        discount:"23% off",
        size:"M",
        color:"White",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/65921470_020_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/65921470_020_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"Standard Cloth Refine Button-Up Polo Sweater",
        price:"59.00",
        discount:"23% off",
        size:"M",
        color:"Brown",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/58731894_040_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/58731894_040_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"adidas 3-Stripe CLX Short",
        price:"35.00",
        discount:"23% off",
        size:"M",
        color:"black",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/59976969_006_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/59976969_006_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"'47 New York Yankees Classic Baseball Hat",
        price:"29.00",
        discount:"23% off",
        size:"M",
        color:"Grey",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/61526943_060_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/61526943_060_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"Levis Skate Varsity Jacket",
        price:"129.00",
        discount:"23% off",
        size:"M",
        color:"Red",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66181173_020_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66181173_020_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"Utopia Paneled Crew Neck Sweatshirt",
        price:"69.00",
        discount:"23% off",
        size:"M",
        color:"Brown",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/63628028_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/63628028_001_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"Mac Miller Albums Pocket Tee",
        price:"36.00",
        discount:"23% off",
        size:"M",
        color:"Black",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66209511_030_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66209511_030_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"Polo Ralph Lauren Bear Hoodie Sweater",
        price:"328.00",
        discount:"23% off",
        size:"M",
        color:"Green",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/64308596_006_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/64308596_006_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"Reebok LT Court Sneaker",
        price:"100.00",
        discount:"23% off",
        size:"M",
        color:"White",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/64791379_004_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/64791379_004_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"Standard Cloth French Terry Cardigan",
        price:"34.00",
        discount:"23% off",
        size:"M",
        color:"Grey",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/64859051_049_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/64859051_049_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"The Ragged Priest Nebular Puffer Jacket",
        price:"140.00",
        discount:"23% off",
        size:"M",
        color:"Blue",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/62202189_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/62202189_001_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"Alpha Industries MA-1 Quilted Flight Jacket",
        price:"200.00",
        discount:"23% off",
        size:"M",
        color:"Black",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/64544315_032_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/64544315_032_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"UO Quilted Pattern Shirt Jacket",
        price:"99.00",
        discount:"23% off",
        size:"M",
        color:"Green",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/67277483_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/67277483_001_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=720",
        name:"True Religion Metallic Logo Jogger Pant",
        price:"99.00",
        discount:"23% off",
        size:"M",
        color:"Black",
        brand:"adidas",
    }
]

}
