let All_data = {
    women:[{
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/65311326_093_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/65311326_093_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"BDG High-Waisted Flare Jean—Indigo Craft",
        price:"119.00",
        discount:"15% off",
        size:"M",
        color:"rgb(60,86,113)",
        brand:"adidas",

    },
   
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/58977810_065_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/58977810_065_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Converse Chuck Taylor All Star Canvas Platform High Top Sneaker",
        price:"79.00",
        discount:"50% off",
        size:"M",
        color:"pink",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66397688_000_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66397688_000_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"UO Moon Notch Neck Top",
        price:"45.00",
        discount:"50% off",
        size:"S",
        color:"black",
        brand:"nike",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/67047191_030_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/67047191_030_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Urban Renewal Remnants Lettuce Edge Set",
        price:"95.00",
        discount:"5% off",
        size:"S",
        color:"green",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66331653_004_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66331653_004_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Urban Renewal Remnants Wide-Leg Check Pant",
        price:"49.00",
        discount:"52% off",
        size:"M",
        color:"gray",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/65727042_030_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/65727042_030_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Urban Renewal Remnants Wide-Leg Check Pant",
        price:"29.00",
        size:"S",
        color:"green",
        color:"rgb(44,100,101)",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66211160_010_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66211160_010_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"BDG Corduroy Dipped-Waistband Pant",
        price:"75.00",
        discount:"2% off",
        size:"M",
        color:"white",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/63000095_020_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/63000095_020_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"BDG High-Waisted Skate Pant",
        price:"75.00",
        discount:"2% off",
        size:"M",
        color:"rgb(211,85,0)",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66165705_034_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66165705_034_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Out From Under Quincy Seamed Hoodie Sweatshirt",
        price:"75.00",
        discount:"2% off",
        size:"M",
        color:"rgb(194,216,147)",
        color:"green",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66165010_001_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66165010_001_f?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"UO Rozi Blouse",
        price:"75.00",
        discount:"2% off",
        size:"M",
        color:"rgb(194,216,147)",
        color:"black",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/63696751_060_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/63696751_060_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Wide Wale Corduroy Bucket Hat",
        price:"75.00",
        discount:"2% off",
        size:"M",
        color:"red",
        color:"rgb(194,red,147)",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66276817_020_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66276817_020_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Out From Under Palmer Short",
        price:"75.00",
        discount:"2% off",
        size:"M",
        color:"rgb(87,40,19)",
        color:"orange",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/67084061_000_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/67084061_000_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Out From Under Theia Striped Sleep Short",
        price:"75.00",
        discount:"2% off",
        size:"M",
        color:"white",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/65686834_105_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/65686834_105_d?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Out From Under Kit Lettuce Edge Short",
        price:"35.00",
        discount:"2% off",
        size:"M",
        color:"rgb(60,86,113)",
        brand:"adidas",
    },
    {
        img1:"https://images.urbndata.com/is/image/UrbanOutfitters/66006719_011_b?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        img2:"https://images.urbndata.com/is/image/UrbanOutfitters/66006719_011_e?$xlarge$&fit=constrain&fmt=webp&qlt=80&wid=360",
        name:"Out From Under Claire High-Rise Legging",
        price:"55.00",
        discount:"2% off",
        size:"M",
        color:"white",
        brand:"adidas",
    },
]

}